algoritmo "semnome"
// Função :
// Autor :
// Data : 19/06/2019
// Seção de Declarações 
var
matriculas:vetor [1..6] de real
nomes:vetor [1..6] de literal
i:inteiro
inicio
// Seção de Comandos
para i de 1 ate 6 faca
   escreva ("o tamanho de seu pipi")
   leia (matriculas[i])
   escreva 1("nome do ipip")
   leia (nomes[i])
fimpara
para i de 1 ate 6 faca
 escreval (matriculas[i] "-" nome[i])
fimpara
fimalgoritmo
