algoritmo "semnome"
// Função :
// Autor :
// Data : 24/06/2019
// Seção de Declarações 
var
anos,cigarros,maco,resultado:real
inicio
// Seção de Comandos
escreval ("Quantia de anos")
leia (anos)
anos<-anos*365
escreval ("Quantia de cigarros")
leia (cigarros)
escreval ("Valor dos maço")
leia (maco)
resultado<-maco*anos

escreval ("Foi gasto um total de: ","R$",resultado,)



fimalgoritmo
