algoritmo "semnome"
// Função :
// Autor :
// Data : 12/06/2019
// Seção de Declarações 
var
numero:inteiro
inicio
// Seção de Comandos
//entrada
escreva "Qual o numero para comparar"
leia (numero)
//processamento
se numero<10   entao
escreva(" ")
escreval ("o numero é menor que 10")
senao
escreva(" ")
escreva ("o numero é maior ou igual a 10")
//saida
fimse


fimalgoritmo
