algoritmo "semnome"
// Função :
// Autor :
// Data : 24/06/2019
// Seção de Declarações 
var
valor1,valor2,soma,produtos,quociente:real
inicio
// Seção de Comandos
escreval ("Valor um: ")
leia (valor1)
escreval ("Valor dois: ")
leia (valor2)

soma<-valor1+valor2
produtos<-valor1*valor2
quociente<-valor1/valor2

escreval ("A soma é de: ",soma)
escreval ("O produto dos valores é de: ",produtos)
escreval ("a divisao dos valores é de: ",quociente)

fimalgoritmo
