algoritmo "semnome"
// Função :
// Autor :
// Data : 10/06/2019
// Seção de Declarações 
var
a,b,c,delta,x1,x2: real
inicio
// Seção de Comandos
escreva ("digite valor da variavel A")
leia (a)
escreva ("digite valor da variavel B")
leia (b)
escreva ("digite valor da variavel C")
leia (c)
delta <- b*b-4*a*c
x1 <- (-b + delta^(1/2))/(2*a)
x2 <- (-b - delta^(1/2))/(2*a)
fimalgoritmo
